//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string BlogTitle { get; set; }
        public string BlogDate { get; set; }
        public Nullable<int> Likes { get; set; }
        public Nullable<int> Comments { get; set; }
        public byte[] BlogImage { get; set; }
        public string BlogDescription { get; set; }
        public string imgCon { get; set; }
    }
}
