//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DietitianProfile
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string TypeofDietitian { get; set; }
        public string Quote { get; set; }
        public string Qualifications { get; set; }
        public string Speciality { get; set; }
        public string Messenger { get; set; }
        public byte[] DietitianPhoto { get; set; }
        public string photoCon { get; set; }
    }
}
