//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberShip
    {
        public int Id { get; set; }
        public string MainCategory { get; set; }
        public string Period { get; set; }
        public string Fee { get; set; }
        public string StartDate { get; set; }
        public string Payment { get; set; }
        public string CardNumber { get; set; }
        public string ExpiryDate { get; set; }
        public string CVV { get; set; }
        public string Email { get; set; }
    }
}
